# Setting java 1.8 
language: android
jdk:
  - oraclejdk8

sudo: required # disables container-based builds which have a maximum of 4GB of memory

# caching as advised by travis
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

env:
  matrix:
  - EMULATOR_API_LEVEL=23  ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-23
  - EMULATOR_API_LEVEL=22  ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-22
  - EMULATOR_API_LEVEL=21  ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-21
  - EMULATOR_API_LEVEL=19  ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-19

  global:
    - ANDROID_API_LEVEL=27
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3
    - ADB_INSTALL_TIMEOUT=20 # wait up to 20 minutes for adb to connect to emulator (2 minutes by default)
    - ANDROID_ABI=armeabi-v7a
    
android:
  components:
    # Base components 
    - tools # to get the new `repository-11.xml`
    - tools # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools   
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION # get the build tools version to build the project

    # used sdk versions
    - android-$ANDROID_API_LEVEL # get the android sdk version to build the project
    - android-$EMULATOR_API_LEVEL # get the android sdk version for the emulator

    # Get the latest version of additional components
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services

    # Specify the needed emulator
    - $ANDROID_EMULATOR_IMAGE

licenses:
  - 'android-sdk-license-.+'
  - '.+'

# Emulator Management: Create, Start and Wait
before_install:
  - echo $ANDROID_TARGET 
  - echo $ANDROID_ABI
  - adb logcat > logcat.log & 

install:
  - sdkmanager --list || true # List all available targets, device definitions and AVDs.
  # Update sdk tools to latest version and install/update components
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platform-tools"
  - echo yes | sdkmanager "build-tools;"$ANDROID_BUILD_TOOLS_VERSION
  - echo yes | sdkmanager "platforms;android-"$ANDROID_API_LEVEL # Latest platform required by SDK tools

  - echo yes | sdkmanager "extras;android;m2repository"
  - echo yes | sdkmanager "extras;google;m2repository"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

  - echo yes | sdkmanager --update
  - echo yes | sdkmanager --licenses

  # Check components status
  - sdkmanager --list || true

install:
  # List and delete unnecessary components to free space
  - sdkmanager --list || true
  - sdkmanager --uninstall "system-images;android-15;default;armeabi-v7a"
  - sdkmanager --uninstall "system-images;android-16;default;armeabi-v7a"
  - sdkmanager --uninstall "system-images;android-17;default;armeabi-v7a"
  - sdkmanager --uninstall "system-images;android-18;default;armeabi-v7a"
  - sdkmanager --uninstall "system-images;android-19;default;armeabi-v7a"
  - sdkmanager --uninstall "system-images;android-21;default;armeabi-v7a"
  - sdkmanager --uninstall "extras;google;google_play_services"
  - sdkmanager --uninstall "extras;android;support"
  - sdkmanager --uninstall "platforms;android-10"
  - sdkmanager --uninstall "platforms;android-15"
  - sdkmanager --uninstall "platforms;android-16"
  - sdkmanager --uninstall "platforms;android-17"
  - sdkmanager --uninstall "platforms;android-18"
  - sdkmanager --uninstall "platforms;android-19"
  - sdkmanager --uninstall "platforms;android-20"
  - sdkmanager --uninstall "platforms;android-21"
  - sdkmanager --uninstall "build-tools;21.1.2"
  # Update sdk tools to latest version and install/update components
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platforms;android-26" # Latest platform required by SDK tools
  - echo yes | sdkmanager "platforms;android-${API}" # Android platform required by emulator
  - echo yes | sdkmanager "extras;android;m2repository"
  - echo yes | sdkmanager "extras;google;m2repository"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  - echo yes | sdkmanager "$EMULATOR" # Install emulator system image
  # Create and start emulator
  - echo no | avdmanager create avd -n acib -k "$EMULATOR" -f --abi "$ABI" --tag "$TAG"
  - emulator -avd acib -engine classic -no-window -camera-back none -camera-front none -verbose -qemu -m 512 &
  # Start adbd, wait for device connected and show android serial
  - adb wait-for-device get-serialno
  # Show version and download Gradle Wrapper if it's not already cached
  - cd ${TRAVIS_BUILD_DIR}/${DIR} && ./gradlew --version
  # Clean project and download missing dependencies and components
  - cd ${TRAVIS_BUILD_DIR}/${DIR} && ./gradlew clean build
  # Check components status
  - sdkmanager --list || true

before_script:
  # Create and start the emulator
  - sdkmanager "system-images;android-"$EMULATOR_API_LEVEL";google_apis;armeabi-v7a"
  - echo no | avdmanager -v create avd -f -n test -k "system-images;android-"$EMULATOR_API_LEVEL";google_apis;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

  - android-wait-for-emulator

  # Turn off animations
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &

  # Wake up
  - adb shell input keyevent 82 &
  - adb shell input keyevent 1 &
script:
  - ./gradlew test # Local unit test
  - ./gradlew connectedAndroidTest # Instrumented unit test
  - ./gradlew lint #maybe at some point
  #- ./gradlew clean test build
after_script:
  - echo $ANDROID_TARGET 
  - echo $ANDROID_ABI
  - cat /home/travis/build/sky-map-team/stardroid/sdk-messaging/build/outputs/lint-results-debug.xml
  - cat /home/travis/build/sky-map-team/stardroid/sdk/build/reports/androidTests/connected/index.html
