blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: mailto:skymapdevs@gmail.com
    about: For general questions, email the maintainers directly.
  - name: Google Play Store
    url: https://play.google.com/store/apps/details?id=com.google.android.stardroid
    about: Download Sky Map or join the beta program.
